# Generated by Django 5.0.3 on 2024-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_answeroption_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
